jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest
  build_and_deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
          platform: managed
          region: europe-west1
          service-name: hello
          unauthenticated: true
      - run:
          command: |
            pytest
          name: Run tests
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.0
version: 2.1
workflows:
  build_and_deploy_to_managed_workflow:
    jobs:
      - build_test
      - build_and_deploy